#@TYPE: Machine
#@NAME: Nvidia Jetson AGX Thor dev kit
#@DESCRIPTION: Nvidia Jetson AGX Thor dev kit (T5000 module)

TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0000;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0000;boardrev=;bup_type=kernel"
KERNEL_DEVICETREE ?= "tegra254-p3737-0000+p3701-0000-nv.dtb"

require conf/machine/include/agx-thor.inc
require conf/machine/include/devkit-wifi.inc
