#
# nvfancontrol config for Jetson Thor (single fan)
# Thor DevKit has one PWM fan at hwmon6/pwm1
#

POLLING_INTERVAL 2

# pwm-fan-1 (hwmon6/pwm1)
<FAN 1>
	TMARGIN DISABLED
	FAN_GOVERNOR pid {
		STEP_SIZE 10
	}
	FAN_PROFILE cool {
		#TEMP 	HYST	PWM	RPM
		0	0 	102 	1000
		24	0 	127	2000
		31	0	163	3000
		36	0	255	4000
		125	0	255	4000
	}
	THERMAL_GROUP 0 {
		#Thermal-Zone Coeffs Max-Temp
		CPU-therm 20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 0
		GPU-therm 20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 0
		SOC0-therm 20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 0
		SOC1-therm 20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 0
		SOC2-therm 20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 0
	}
	FAN_DEFAULT_CONTROL open_loop
	FAN_DEFAULT_PROFILE cool
	FAN_DEFAULT_GOVERNOR pid
